/* eslint-disable @typescript-eslint/no-explicit-any */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	bootstrap: () => typedError<BootstrapSnapshot_Serialize, CommandError>(__TAURI_INVOKE("bootstrap")),
	listConversations: (request: ListConversationsRequest) => typedError<ConversationPage, CommandError>(__TAURI_INVOKE("list_conversations", { request })),
	loadTimeline: (request: LoadTimelineRequest) => typedError<TimelinePage, CommandError>(__TAURI_INVOKE("load_timeline", { request })),
	loadAgentTree: (request: LoadAgentTreeRequest) => typedError<AgentTreePage, CommandError>(__TAURI_INVOKE("load_agent_tree", { request })),
	loadEventDetail: (request: LoadEventDetailRequest) => typedError<EventDetailSnapshot, CommandError>(__TAURI_INVOKE("load_event_detail", { request })),
	loadApprovals: (request: LoadApprovalsRequest) => typedError<ApprovalPage, CommandError>(__TAURI_INVOKE("load_approvals", { request })),
	loadApprovalDetail: (request: LoadApprovalDetailRequest) => typedError<ApprovalDetailSnapshot, CommandError>(__TAURI_INVOKE("load_approval_detail", { request })),
	loadApprovalQuestions: (request: LoadApprovalQuestionsRequest) => typedError<ApprovalQuestionPage, CommandError>(__TAURI_INVOKE("load_approval_questions", { request })),
	createConversation: (request: CreateConversationRequest) => typedError<ConversationSummary, CommandError>(__TAURI_INVOKE("create_conversation", { request })),
	submitMessage: (request: SubmitMessageRequest) => typedError<SubmissionSnapshot, CommandError>(__TAURI_INVOKE("submit_message", { request })),
	steerRun: (request: SteerRunRequest) => typedError<null, CommandError>(__TAURI_INVOKE("steer_run", { request })),
	respondToApproval: (request: RespondToApprovalRequest) => typedError<null, CommandError>(__TAURI_INVOKE("respond_to_approval", { request })),
	interruptRun: (request: InterruptRunRequest) => typedError<null, CommandError>(__TAURI_INVOKE("interrupt_run", { request })),
	archiveConversation: (request: ArchiveConversationRequest) => typedError<null, CommandError>(__TAURI_INVOKE("archive_conversation", { request })),
	inspectWorkspace: (request: InspectWorkspaceRequest) => typedError<InspectorSnapshot, CommandError>(__TAURI_INVOKE("inspect_workspace", { request })),
};

/* Types */
export type AgentSnapshot = {
	id: string,
	parentId: string | null,
	provider: ProviderId,
	label: string,
	summary: string | null,
	status: AgentStatus,
};

export type AgentStatus = "queued" | "running" | "waiting" | "completed" | "interrupted" | "failed";

export type AgentTreeItem = {
	agent: AgentSnapshot,
	depth: number,
};

export type AgentTreePage = {
	runId: string | null,
	items: AgentTreeItem[],
	nextCursor: string | null,
};

export type AppEvent = { kind: "conversationChanged"; sequence: string; conversationId: string } | { kind: "runChanged"; sequence: string; conversationId: string; runId: string } | { kind: "reloadRequired"; sequence: string };

export type ApprovalDetailSnapshot = {
	id: string,
	operation: string,
	scope: string,
	input: UserInputRequest | null,
	details: ApprovalDetails | null,
	questionCount: number,
	truncated: boolean,
};

export type ApprovalDetails = { kind: "commandExecution"; command: string | null; cwd: string | null } | { kind: "fileChange"; changes: FileChange[]; grantRoot: string | null; reason: string | null } | { kind: "permissionProfile"; cwd: string; profile: PermissionProfile };

export type ApprovalListKind = "pending" | "history";

export type ApprovalPage = {
	items: ApprovalSnapshot[],
	nextCursor: string | null,
};

export type ApprovalQuestionPage = {
	items: ApprovalQuestionPreview[],
	totalCount: number,
	nextCursor: string | null,
};

export type ApprovalQuestionPreview = {
	id: string,
	header: string,
	question: string,
	options: UserInputOption[] | null,
	isOther: boolean,
	isSecret: boolean,
	truncated: boolean,
};

export type ApprovalResponse = { kind: "approved" } | { kind: "denied" } | { kind: "answer"; value: string } | { kind: "answers"; value: { [key in string]: string[] } };

export type ApprovalSnapshot = {
	id: string,
	runId: string,
	agentId: string,
	provider: ProviderId,
	operation: string,
	scope: string,
	status: ApprovalStatus,
	responsePending: boolean,
};

export type ApprovalStatus = "pending" | "approved" | "denied" | "answered" | "cancelled" | "failed";

export type ArchiveConversationRequest = {
	conversationId: string,
};

export type BootstrapSnapshot = BootstrapSnapshot_Serialize | BootstrapSnapshot_Deserialize;

export type BootstrapSnapshot_Deserialize = {
	providers: ProviderInstallation[],
	startupDiagnostic: CommandError | null,
};

export type BootstrapSnapshot_Serialize = {
	providers: ProviderInstallation[],
	startupDiagnostic?: CommandError | null,
};

export type CleanupBlocker = "notOwned" | "missingWorktree" | "modifiedTrackedFiles" | "untrackedFiles" | "uniqueCommits" | "activeProcess";

export type CleanupSnapshot = {
	eligible: boolean,
	blocker: CleanupBlocker | null,
};

export type CommandError = {
	code: string,
	message: string,
	action: string | null,
};

export type ConversationPage = {
	items: ConversationSummary[],
	nextCursor: string | null,
};

export type ConversationSummary = {
	id: string,
	title: string,
	workspaceId: string | null,
	archived: boolean,
	projectRoot: string | null,
	currentRunId: string | null,
	provider: ProviderId | null,
	runStatus: RunStatus | null,
	rollupStatus: RollupStatus | null,
	agents: AgentSnapshot[],
	agentsTruncated: boolean,
};

export type ConversationWorkspaceRequest = { kind: "projectless" } | { kind: "isolated"; path: string } | { kind: "direct"; path: string };

export type CreateConversationRequest = {
	title: string,
	objective: string,
	constraints: string[],
	workspace: ConversationWorkspaceRequest,
	routingProfile: RoutingProfile,
};

export type CurrentRunSnapshot = {
	id: string,
	provider: ProviderId,
	status: RunStatus,
};

export type EventDetailSnapshot = {
	id: string,
	content: string,
	contentBytes: string,
	truncated: boolean,
};

export type FileChange = {
	path: string,
	change: FileChangeKind,
};

export type FileChangeKind = { kind: "add" } | { kind: "delete" } | { kind: "update"; movePath: string | null };

export type FileSystemAccess = "read" | "write" | "deny";

export type FileSystemPath = { type: "path"; path: string } | { type: "glob_pattern"; pattern: string } | { type: "special"; value: SpecialPath };

export type InspectWorkspaceRequest = {
	conversationId: string,
};

export type InspectorSnapshot = {
	workspace: WorkspaceSnapshot,
	cleanup: CleanupSnapshot,
	currentRun: CurrentRunSnapshot | null,
	routing: RoutingSnapshot | null,
	handoff: string | null,
	activeDescendantCount: number,
	agentsTruncated: boolean,
};

export type InterruptRunRequest = {
	runId: string,
};

export type ListConversationsRequest = {
	cursor: string | null,
	limit: number,
};

export type LoadAgentTreeRequest = {
	conversationId: string,
	cursor: string | null,
	limit: number,
};

export type LoadApprovalDetailRequest = {
	approvalId: string,
};

export type LoadApprovalQuestionsRequest = {
	approvalId: string,
	cursor: string | null,
	limit: number,
};

export type LoadApprovalsRequest = {
	conversationId: string,
	cursor: string | null,
	limit: number,
	kind: ApprovalListKind,
};

export type LoadEventDetailRequest = {
	eventId: string,
};

export type LoadTimelineRequest = {
	conversationId: string,
	cursor: string | null,
	limit: number,
};

export type MessageRole = "user" | "assistant";

export type PermissionEntry = {
	access: FileSystemAccess,
	path: FileSystemPath,
};

export type PermissionProfile = {
	entries: PermissionEntry[] | null,
	globScanMaxDepth: string | null,
	read: string[] | null,
	write: string[] | null,
	networkEnabled: boolean | null,
};

export type ProviderCapability = "streaming" | "steering" | "deferredApproval" | "interruption" | "resume" | "childAgents";

export type ProviderEvaluation = {
	provider: ProviderId,
	eligible: boolean,
	blockers: RoutingBlocker[],
};

export type ProviderId = "codex" | "claude";

export type ProviderInstallation = {
	id: ProviderId,
	installed: boolean,
	available: boolean,
	version: string | null,
	diagnostic: string | null,
	capabilities: ProviderCapability[],
};

export type ProviderRank = {
	provider: ProviderId,
	recentRootRuns: string,
	stableOrder: number,
};

export type ProviderUnavailability = "notInstalled" | "unsupportedVersion" | "unauthenticated" | "unhealthy" | "quotaBlocked";

export type RespondToApprovalRequest = {
	approvalId: string,
	response: ApprovalResponse,
};

export type RollupStatus = "needsAttention" | "active" | "failed" | "interrupted" | "completed";

export type RoutingBlocker = { kind: "unavailable"; value: ProviderUnavailability } | { kind: "missingCapability"; value: ProviderCapability } | { kind: "notReported" };

export type RoutingCriterion = { kind: "manualOverride"; provider: ProviderId } | { kind: "eligibleProviders"; providers: ProviderId[] } | { kind: "requiredCapabilities"; capabilities: ProviderCapability[] } | { kind: "continuity"; provider: ProviderId } | { kind: "rankedCandidates"; candidates: ProviderRank[] } | { kind: "safeFallback"; from: ProviderId; to: ProviderId };

export type RoutingProfile = "balanced" | "bestFit" | "usageBalance";

export type RoutingReason = "manualOverride" | "requiredCapabilities" | "continuity" | "onlyEligibleProvider" | "leastUsed" | "deterministicTieBreak" | "safeFallback";

export type RoutingSnapshot = {
	provider: ProviderId,
	profile: RoutingProfile,
	reason: RoutingReason,
	taskKind: TaskKind,
	overrideProvider: ProviderId | null,
	eligibleProviders: ProviderId[],
	requiredCapabilities: ProviderCapability[],
	evaluations: ProviderEvaluation[],
	rationale: RoutingCriterion[],
	explanation: string,
};

export type RunStatus = "queued" | "running" | "waiting" | "completed" | "interrupted" | "failed";

export type SpecialPath = { kind: "root" } | { kind: "minimal" } | { kind: "project_roots"; subpath: string | null } | { kind: "tmpdir" } | { kind: "slash_tmp" } | { kind: "unknown"; path: string; subpath: string | null };

export type SteerRunRequest = {
	runId: string,
	text: string,
};

export type SubmissionSnapshot = {
	runId: string,
	status: RunStatus,
	provider: ProviderId,
	duplicate: boolean,
	routingExplanation: string,
};

export type SubmitMessageRequest = {
	conversationId: string,
	text: string,
	providerOverride: ProviderId | null,
	commandId: string,
};

export type TaskKind = "implementation" | "review" | "research" | "general";

export type TimelineItem = {
	id: string,
	conversationId: string,
	runId: string,
	agentId: string,
	sequence: string,
	kind: TimelineItemKind,
	role: MessageRole | null,
	content: string,
	contentBytes: string,
	truncated: boolean,
	provider: ProviderId,
};

export type TimelineItemKind = "message" | "tool" | "progress" | "diagnostic" | "lifecycle";

export type TimelinePage = {
	items: TimelineItem[],
	nextCursor: string | null,
	approvals: ApprovalSnapshot[],
	approvalsTruncated: boolean,
	approvalsNextCursor: string | null,
};

export type UserInputOption = {
	label: string,
	description: string,
};

export type UserInputQuestion = {
	id: string,
	header: string,
	question: string,
	options: UserInputOption[] | null,
	isOther: boolean,
	isSecret: boolean,
};

export type UserInputRequest = {
	questions: UserInputQuestion[],
	autoResolutionMs: string | null,
};

export type WorkspaceChange = {
	kind: WorkspaceChangeKind,
	relativePath: string,
};

export type WorkspaceChangeKind = "present" | "added" | "modified" | "deleted" | "renamed" | "copied" | "untracked" | "conflicted";

export type WorkspaceMode = "projectless" | "direct" | "isolated";

export type WorkspaceSnapshot = {
	mode: WorkspaceMode,
	changes: WorkspaceChange[],
	truncated: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
